bad auto-complete... bad

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,7 +68,7 @@ jobs:
             else
               echo "Skipping monitor for non-main branch - no data sent to dashboard"
             fi
-      - run: snyk test --severity-threshold=high --all-projects --detection-depth=10 --scan-all-unmanaged --json > snyk-test-results.json || true # will NOT fail step if any results are found
+      - run: snyk test --severity-threshold=high --all-projects --detection-depth=10 --scan-all-unmanaged --json > snyk-results.json || true # will NOT fail step if any results are found
       - run:
           name: CVE Summary
           command: |
